// @ts-nocheck
import React, { useEffect, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { useAuthStore } from '../../store/authStore';
import { getCompetencyProfile, getSkillGaps } from '../../api/intelligenceApi';
import { learnerDashboardData as data } from './learnerDashboard.data';
import { ArrowRight, Award, Bell, BookOpen, Brain, Check, ChevronRight, Circle, Clock3, Flame, Play, ShieldCheck, Star, Target, TrendingUp, Zap } from 'lucide-react';
import { Area, AreaChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';

const activity = [{ day: 'Mon', hours: 2 }, { day: 'Tue', hours: 1 }, { day: 'Wed', hours: 3 }, { day: 'Thu', hours: 2 }, { day: 'Fri', hours: 4 }, { day: 'Sat', hours: 1 }, { day: 'Sun', hours: 3 }];
const activityIcons = { course: BookOpen, assessment: Target, certificate: Award, competency: TrendingUp };

const SectionHeading = ({ eyebrow, title, action, onAction }) => (
  <div className="mb-5 flex items-end justify-between gap-4">
    <div><p className="text-[10px] font-bold uppercase tracking-[0.18em] text-purple-300">{eyebrow}</p><h2 className="mt-1 text-xl font-semibold tracking-tight text-white">{title}</h2></div>
    {action && <button onClick={onAction} className="flex items-center gap-1 text-xs font-semibold text-slate-400 transition-colors hover:text-white">{action}<ChevronRight size={14} /></button>}
  </div>
);

const ProgressBar = ({ value, color = 'bg-purple-400' }) => <div className="h-1.5 overflow-hidden rounded-full bg-white/10"><div className={`h-full rounded-full ${color}`} style={{ width: `${value}%` }} /></div>;

export const LearnerDashboard = () => {
  const user = useAuthStore(state => state.user);
  const token = useAuthStore(state => state.token);
  const navigate = useNavigate();
  const [loading, setLoading] = useState(true);
  const [profile, setProfile] = useState<any>(null);
  const firstName = user?.name?.split(' ')[0] || 'Learner';

  useEffect(() => {
    let active = true;
    const load = async () => {
      if (token) {
        try { const result = await getCompetencyProfile(token); if (active) setProfile(result); } catch { /* Mock data keeps the dashboard useful when the service is unavailable. */ }
        try { await getSkillGaps(token, 'dummy_role_id'); } catch { /* Skill gaps are replaced by the API when available. */ }
      }
      if (active) setLoading(false);
    };
    load();
    return () => { active = false; };
  }, [token]);

  if (loading) return <div className="space-y-6 pb-24 animate-pulse"><div className="h-48 rounded-2xl bg-white/[.06]" /><div className="grid grid-cols-2 gap-3 lg:grid-cols-6">{[1, 2, 3, 4, 5, 6].map(item => <div key={item} className="h-24 rounded-xl bg-white/[.06]" />)}</div><div className="h-72 rounded-2xl bg-white/[.06]" /></div>;

  const overall = profile?.overallScore ? Math.round(profile.overallScore) : 78;
  const stats = [
    { label: 'Active courses', value: '4', note: '2 due this month', icon: BookOpen, accent: 'text-purple-300' }, { label: 'Completed courses', value: '8', note: '2 this quarter', icon: Check, accent: 'text-emerald-300' }, { label: 'Learning hours', value: '32h', note: '12h this week', icon: Clock3, accent: 'text-sky-300' }, { label: 'Avg. assessment', value: '84%', note: 'Strong momentum', icon: Target, accent: 'text-amber-300' }, { label: 'Certificates', value: '5', note: 'All verified', icon: Award, accent: 'text-pink-300' }, { label: 'Learning streak', value: '7 days', note: 'Keep it going', icon: Flame, accent: 'text-orange-300' },
  ];

  return (
    <div className="space-y-10 pb-28">
      <section className="relative overflow-hidden rounded-2xl border border-white/10 bg-gradient-to-br from-[#211b3a] via-[#151525] to-[#101318] p-6 sm:p-8">
        <div className="absolute -right-16 -top-20 h-64 w-64 rounded-full bg-purple-500/10 blur-3xl" />
        <div className="relative flex flex-col justify-between gap-7 lg:flex-row lg:items-center">
          <div className="max-w-2xl"><div className="mb-3 flex items-center gap-2 text-xs font-semibold uppercase tracking-[0.16em] text-purple-300"><Zap size={14} /> Learner workspace</div><h1 className="text-3xl font-semibold tracking-tight text-white sm:text-4xl">Good morning, {firstName} <span aria-hidden="true">👋</span></h1><p className="mt-3 max-w-xl text-sm leading-6 text-slate-300">Continue your learning journey and build the competencies you need for your next opportunity.</p><div className="mt-6 flex flex-wrap items-center gap-3"><button onClick={() => navigate(`/course/${data.courses[0].id}`)} className="inline-flex items-center gap-2 rounded-lg bg-purple-500 px-4 py-2.5 text-sm font-semibold text-white transition hover:bg-purple-400"><Play size={15} fill="currentColor" /> Continue learning <ArrowRight size={15} /></button><span className="inline-flex items-center gap-2 rounded-lg border border-white/10 bg-white/[.04] px-3 py-2 text-xs text-slate-300"><Flame size={14} className="text-orange-300" /> 7 day streak</span></div></div>
          <div className="flex items-center gap-5 rounded-xl border border-white/10 bg-black/10 px-5 py-4"><div className="relative grid h-20 w-20 place-items-center rounded-full" style={{ background: `conic-gradient(#a78bfa ${overall}%, rgba(255,255,255,.1) 0)` }}><div className="grid h-16 w-16 place-items-center rounded-full bg-[#17172a] text-2xl font-semibold text-white">{overall}</div></div><div><p className="text-xs uppercase tracking-wider text-slate-400">Overall progress</p><p className="mt-1 text-sm font-medium text-white">Capability readiness</p><p className="mt-2 text-xs text-emerald-300">+6% this month</p></div></div>
        </div>
      </section>

      <section className="grid grid-cols-2 gap-3 md:grid-cols-3 lg:grid-cols-6">{stats.map(({ label, value, note, icon: Icon, accent }) => <div key={label} className="rounded-xl border border-white/10 bg-white/[.045] p-4 transition hover:border-white/20 hover:bg-white/[.07]"><Icon size={17} className={accent} /><p className="mt-4 text-2xl font-semibold text-white">{value}</p><p className="mt-1 text-xs font-medium text-slate-300">{label}</p><p className="mt-2 text-[10px] text-slate-500">{note}</p></div>)}</section>

      <section><SectionHeading eyebrow="Priority learning" title="Continue learning" action="View all courses" onAction={() => navigate('/learning-hub')} /><div className="grid gap-4 lg:grid-cols-2">{data.courses.map(course => <article key={course.id} className="overflow-hidden rounded-xl border border-white/10 bg-white/[.045] transition hover:border-purple-300/40"><div className="flex flex-col sm:flex-row"><img src={course.image} alt="" className="h-40 w-full object-cover sm:h-auto sm:w-44" /><div className="flex-1 p-5"><div className="flex items-start justify-between gap-3"><div><p className="text-[10px] uppercase tracking-wider text-purple-300">{course.category}</p><h3 className="mt-1 font-semibold text-white">{course.title}</h3><p className="mt-1 text-xs text-slate-400">with {course.trainer} · {course.level}</p></div><span className="text-lg font-semibold text-purple-200">{course.progress}%</span></div><div className="mt-5"><div className="mb-2 flex justify-between text-[11px] text-slate-400"><span>{course.modules}</span><span>{course.lastAccessed}</span></div><ProgressBar value={course.progress} /></div><button onClick={() => navigate(`/course/${course.id}`)} className="mt-5 inline-flex items-center gap-2 text-xs font-semibold text-white hover:text-purple-300">Continue learning <ArrowRight size={14} /></button></div></div></article>)}</div></section>

      <div className="grid gap-8 xl:grid-cols-[1.15fr_.85fr]"><section><SectionHeading eyebrow="Next up" title="Upcoming assessments" action="View assessments" onAction={() => navigate('/learning-hub')} /><div className="divide-y divide-white/10 overflow-hidden rounded-xl border border-white/10 bg-white/[.045]">{data.assessments.map(item => <div key={item.id} className="flex flex-col gap-4 p-4 sm:flex-row sm:items-center sm:justify-between"><div className="flex items-start gap-3"><div className={`mt-1 grid h-8 w-8 shrink-0 place-items-center rounded-lg ${item.status === 'Due soon' ? 'bg-amber-400/10 text-amber-300' : item.status === 'Completed' ? 'bg-emerald-400/10 text-emerald-300' : 'bg-sky-400/10 text-sky-300'}`}><Target size={15} /></div><div><p className="text-sm font-medium text-white">{item.title}</p><p className="mt-1 text-xs text-slate-400">{item.course} · {item.questions} questions · {item.duration}</p><p className="mt-2 text-[11px] text-slate-500">Deadline: {item.deadline}</p></div></div><div className="flex items-center justify-between gap-3 sm:flex-col sm:items-end"><span className="text-[10px] font-semibold uppercase tracking-wider text-slate-400">{item.status}</span>{item.status !== 'Completed' && <button className="rounded-md border border-white/10 px-3 py-1.5 text-xs font-semibold text-slate-200 hover:border-purple-300/50 hover:text-white">Start</button>}</div></div>)}</div></section><section><SectionHeading eyebrow="Your rhythm" title="Learning activity" /><div className="rounded-xl border border-white/10 bg-white/[.045] p-4"><div className="mb-3 flex items-end justify-between"><div><p className="text-3xl font-semibold text-white">12<span className="text-base text-slate-500"> / 15h</span></p><p className="text-xs text-slate-400">Weekly learning goal</p></div><span className="text-xs font-medium text-emerald-300">80% complete</span></div><div className="h-44"><ResponsiveContainer width="100%" height="100%"><AreaChart data={activity} margin={{ top: 10, right: 5, left: -24, bottom: 0 }}><defs><linearGradient id="learningFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#a78bfa" stopOpacity={0.4} /><stop offset="100%" stopColor="#a78bfa" stopOpacity={0} /></linearGradient></defs><CartesianGrid stroke="rgba(255,255,255,.08)" vertical={false} /><XAxis dataKey="day" tick={{ fill: '#94a3b8', fontSize: 10 }} axisLine={false} tickLine={false} /><YAxis tick={{ fill: '#64748b', fontSize: 10 }} axisLine={false} tickLine={false} /><Tooltip contentStyle={{ background: '#1b1a2b', border: '1px solid rgba(255,255,255,.12)', borderRadius: 8, fontSize: 12 }} /><Area type="monotone" dataKey="hours" stroke="#a78bfa" fill="url(#learningFill)" strokeWidth={2} /></AreaChart></ResponsiveContainer></div></div></section></div>

      <section><SectionHeading eyebrow="Curated for your growth" title="Recommended for you" action="Explore courses" onAction={() => navigate('/learning-hub')} /><div className="grid gap-4 md:grid-cols-3">{data.recommendations.map(course => <article key={course.id} className="overflow-hidden rounded-xl border border-white/10 bg-white/[.045] transition hover:-translate-y-0.5 hover:border-purple-300/40"><img src={course.image} alt="" className="h-32 w-full object-cover" /><div className="p-4"><div className="flex items-center justify-between text-[11px] text-slate-400"><span>{course.level}</span><span className="flex items-center gap-1 text-amber-200"><Star size={12} fill="currentColor" /> {course.rating}</span></div><h3 className="mt-2 font-semibold text-white">{course.title}</h3><p className="mt-1 text-xs text-slate-400">{course.trainer} · {course.duration}</p><p className="mt-4 rounded-md bg-purple-400/10 p-2.5 text-xs leading-5 text-purple-200"><Brain size={13} className="mr-1 inline" /> {course.reason}</p><button onClick={() => navigate('/learning-hub')} className="mt-4 text-xs font-semibold text-white hover:text-purple-300">View course <ArrowRight size={13} className="ml-1 inline" /></button></div></article>)}</div></section>

      <div className="grid gap-8 xl:grid-cols-[1.1fr_.9fr]"><section><SectionHeading eyebrow="Capability intelligence" title="My competencies" action="Full profile" onAction={() => navigate('/competency-profile')} /><div className="rounded-xl border border-white/10 bg-white/[.045] p-5"><div className="space-y-5">{data.competencies.map(item => <div key={item.name}><div className="mb-2 flex items-center justify-between text-xs"><span className="font-medium text-slate-200">{item.name}</span><span className="text-slate-400">{item.score}% · {item.level}</span></div><div className="relative"><ProgressBar value={item.score} color="bg-emerald-300" /><span className="absolute -top-1.5 h-4 w-px bg-purple-300/70" style={{ left: `${item.target}%` }} /></div><p className="mt-1 text-[10px] text-slate-500">Target level: {item.target}%</p></div>)}</div></div></section><section><SectionHeading eyebrow="Close the gap" title="Your skill gaps" action="View analysis" onAction={() => navigate('/skill-gap')} /><div className="space-y-3">{data.skillGaps.map(gap => <div key={gap.name} className="rounded-xl border border-white/10 bg-white/[.045] p-4"><div className="flex items-center justify-between"><div><h3 className="text-sm font-medium text-white">{gap.name}</h3><p className="mt-1 text-xs text-slate-400">{gap.current} <span className="mx-1 text-slate-600">→</span> {gap.target}</p></div><span className="text-lg font-semibold text-amber-200">{gap.score}%</span></div><ProgressBar value={gap.score} color="bg-amber-300" /><p className="mt-3 text-xs text-slate-400">Recommended: <span className="text-slate-200">{gap.recommendation}</span></p><button onClick={() => navigate('/skill-gap')} className="mt-3 text-xs font-semibold text-purple-200 hover:text-white">View recommendation <ArrowRight size={13} className="ml-1 inline" /></button></div>)}</div></section></div>

      <section><SectionHeading eyebrow="Your next opportunity" title="Recommended learning path" /><div className="overflow-x-auto rounded-xl border border-white/10 bg-white/[.045] p-5"><div className="flex min-w-[680px] items-start">{data.learningPath.map((item, index) => <React.Fragment key={item.title}><div className="flex w-36 flex-col items-center text-center"><div className={`grid h-9 w-9 place-items-center rounded-full border ${item.state === 'complete' ? 'border-emerald-300/50 bg-emerald-300/10 text-emerald-300' : item.state === 'current' ? 'border-purple-300 bg-purple-400/20 text-purple-200 shadow-[0_0_20px_rgba(167,139,250,.2)]' : 'border-white/15 text-slate-500'}`}>{item.state === 'complete' ? <Check size={15} /> : item.state === 'current' ? <Play size={13} fill="currentColor" /> : <Circle size={10} />}</div><p className={`mt-3 text-xs ${item.state === 'current' ? 'font-semibold text-white' : 'text-slate-400'}`}>{item.title}</p><p className="mt-1 text-[10px] uppercase tracking-wider text-slate-600">{item.state}</p></div>{index < data.learningPath.length - 1 && <div className={`mt-4 h-px flex-1 ${item.state === 'complete' ? 'bg-emerald-300/50' : 'bg-white/10'}`} />}</React.Fragment>)}</div></div></section>

      <div className="grid gap-8 lg:grid-cols-2"><section><SectionHeading eyebrow="Proof of progress" title="Certificates" action="View all" onAction={() => navigate('/achievements')} /><div className="grid gap-3 sm:grid-cols-2">{data.certificates.map(certificate => <div key={certificate.id} className="rounded-xl border border-white/10 bg-white/[.045] p-4"><div className="mb-4 flex items-center justify-between"><div className="grid h-9 w-9 place-items-center rounded-lg bg-amber-300/10 text-amber-200"><Award size={17} /></div><span className="flex items-center gap-1 text-[10px] font-semibold uppercase tracking-wider text-emerald-300"><ShieldCheck size={13} /> Verified</span></div><h3 className="text-sm font-semibold text-white">{certificate.title}</h3><p className="mt-1 text-xs text-slate-400">{certificate.course}</p><p className="mt-3 text-[10px] text-slate-500">Issued {certificate.date} · {certificate.id}</p><div className="mt-4 flex gap-3"><button className="text-xs font-semibold text-purple-200 hover:text-white">View</button><button className="text-xs font-semibold text-slate-400 hover:text-white">Download</button></div></div>)}</div></section><section><SectionHeading eyebrow="Momentum" title="Recent activity" /><div className="rounded-xl border border-white/10 bg-white/[.045] p-4">{data.activity.map(item => { const Icon = activityIcons[item.type]; return <div key={item.text} className="flex gap-3 border-b border-white/10 py-3 last:border-0"><div className="grid h-7 w-7 shrink-0 place-items-center rounded-full bg-purple-400/10 text-purple-200"><Icon size={13} /></div><div><p className="text-xs text-slate-200">{item.text}</p><p className="mt-1 text-[10px] text-slate-500">{item.time}</p></div></div>; })}</div></section></div>

      <section><SectionHeading eyebrow="Stay informed" title="Notifications" action="View all" onAction={() => navigate('/notifications')} /><div className="grid gap-3 md:grid-cols-3">{data.notifications.map(item => <button key={item.text} onClick={() => navigate('/notifications')} className="rounded-xl border border-white/10 bg-white/[.045] p-4 text-left transition hover:border-white/20"><div className="flex items-start gap-3"><Bell size={15} className={item.unread ? 'text-purple-300' : 'text-slate-500'} /><div><p className="text-xs text-slate-200">{item.text}</p><p className="mt-2 text-[10px] text-slate-500">{item.time}{item.unread && <span className="ml-2 inline-block h-1.5 w-1.5 rounded-full bg-purple-300" />}</p></div></div></button>)}</div></section>
    </div>
  );
};